networks:
  app-network:
    driver: bridge

volumes:
  app_db_volume:

services:
  postgres:
    container_name: app_postgres
    restart: unless-stopped
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - app_db_volume:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    container_name: app_nginx
    restart: unless-stopped
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www
      - ./images/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./images/nginx/templates:/etc/nginx/templates/
    depends_on:
      - php
    networks:
      - app-network

  php:
    container_name: app_php
    build: ./images/php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./www:/var/www
      - ./images/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    command: >
      sh -c " true &&       
              composer install &&
              ./yii migrate --interactive=0 &&
              composer dumpautoload -o &&
              docker-php-entrypoint php-fpm"
    depends_on:
      - postgres
    networks:
      - app-network
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}

  open-api:
    container_name: app_open_api
    image: swaggerapi/swagger-ui:latest
    restart: unless-stopped
    environment:
      - SWAGGER_JSON=/mnt/openapi.json
    volumes:
      - ./openapi.json:/mnt/openapi.json
    depends_on:
      - php
    ports:
      - "8080:8080"
    networks:
      - app-network

